backend:
  name: github
  repo: gabrielpoca/gabrielpoca.com
  base_url: https://auth.gabrielpoca.com
  auth_scope: public_repo

media_folder: ''
public_folder: ''

collections:
  - name: 'post'
    label: 'Post'
    folder: 'priv/site/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{year}}-{{month}}-{{day}}-{{title}}/{{slug}}'
    editor:
      preview: false
    fields:
      - name: 'layout'
        widget: 'hidden'
        default: "_includes/post_layout.slime"
      - name: 'tag'
        widget: 'hidden'
        default: ["post"]
      - label: 'Cover'
        name: 'cover'
        widget: 'image'
        allow_multiple: false
        required: false
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'date'
        format: 'YYYY-MM-DD'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

  - name: 'book_reviews'
    label: 'Book Reviews'
    extension: yml
    folder: 'priv/site/_data/book_reviews'
    media_folder: '../../books/_covers'
    public_folder: 'books/_covers'
    create: true
    slug: '{{year}}{{month}}{{day}}_{{title}}'
    editor:
      preview: false
    fields:
      - label: 'ISBN'
        name: 'isbn'
        widget: 'string'
        required: false
      - label: 'ISBN13'
        name: 'isbn13'
        widget: 'string'
        required: false
      - label: 'Goodreads ID'
        name: 'goodreads'
        widget: 'string'
        required: false
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Author'
        name: 'author'
        widget: 'string'
      - label: 'Date Read'
        name: 'dateRead'
        widget: 'date'
        format: 'YYYY-MM-DD'
      - label: 'Rating'
        name: 'rating'
        widget: 'number'
        min: 1
        max: 5
      - label: 'Review'
        name: 'review'
        widget: 'markdown'
        required: false
      - label: 'Cover'
        name: 'cover'
        widget: 'image'
        allow_multiple: false
