name: Deploy Site

on:
  push:
    branches: [gp-annex]

jobs:
  site:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        otp:
          - 24.0
        elixir:
          - 1.12.1
        rust:
          - stable

    steps:
      - run: 'git config --global url."https://github.com/".insteadOf git@github.com:'
      - run: 'git config --global url."https://".insteadOf git://'

      - uses: actions/checkout@v2

      - run: |
          git config user.email "you@example.com"
          git config user.name "Your Name"

      - name: Install git-annnex
        run: |
          sudo apt-get update
          sudo apt-get install -y git-annex

      - name: Setup git-annex
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # git-annex init
          # git annex enableremote
          git annex enableremote backblaze
          # git annex initremote backblaze type=S3 signature=v4 host=s3.us-west-002.backblazeb2.com bucket=gabrielpoca-site protocol=https encryption=none

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Restore Cache
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            assets/node_modules
          key: npm-v3-${{ hashFiles('priv/site/assets/package-lock.json') }}

      - name: Restore Cache
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            _site
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-v3-${{ hashFiles('mix.lock') }}

      - run: mix deps.get

      - run: cd priv/site/assets && npm install

      - run: cd priv/site/assets && NODE_ENV=production npx tailwindcss -o ../global.css -i global.css --minify

      - run: MIX_ENV=prod mix compile

      - run: MIX_ENV=prod mix still.compile

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
