name: Deploy Site

on:
  push:
    branches: [ master ]

jobs:
  site:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp:
          - 23
        elixir:
          - 1.10.4
        rust:
          - stable

    steps:
      - run: 'git config --global url."https://github.com/".insteadOf git@github.com:'
      - run: 'git config --global url."https://".insteadOf git://'
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '23.0'
          elixir-version: '1.10.4'
      - run: mix deps.get
      - run: MIX_ENV=prod mix still.compile
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
